#!/usr/bin/env python3
"""Generate Python typed contract objects from OpenAPI components schemas."""

from __future__ import annotations

import argparse
import difflib
import json
import pathlib
import re
import sys
from typing import Any

ROOT = pathlib.Path(__file__).resolve().parents[3]
OPENAPI_PATH = ROOT / "packages/contracts/openapi/v1.json"
OUTPUT_PATH = ROOT / "packages/contracts/python/contracts_v1.py"

IDENT_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def resolve_ref_name(ref: str) -> str:
    return ref.rsplit("/", 1)[-1]


def quote_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def is_valid_identifier(name: str) -> bool:
    return bool(IDENT_RE.match(name))


def schema_to_type(schema: dict[str, Any] | None) -> str:
    if not schema:
        return "Any"

    if "$ref" in schema:
        return resolve_ref_name(schema["$ref"])

    if "enum" in schema:
        literals = ", ".join(repr(v) for v in schema["enum"])
        return f"Literal[{literals}]"

    if "oneOf" in schema:
        return join_union([schema_to_type(item) for item in schema["oneOf"]])

    if "anyOf" in schema:
        return join_union([schema_to_type(item) for item in schema["anyOf"]])

    schema_type = schema.get("type")

    if isinstance(schema_type, list):
        non_null = [t for t in schema_type if t != "null"]
        has_null = len(non_null) != len(schema_type)
        if not non_null:
            return "None"
        base = schema_to_type({**schema, "type": non_null[0]})
        return f"{base} | None" if has_null else base

    if schema_type == "string":
        return "str"
    if schema_type == "integer":
        return "int"
    if schema_type == "number":
        return "float"
    if schema_type == "boolean":
        return "bool"
    if schema_type == "null":
        return "None"
    if schema_type == "array":
        return f"list[{schema_to_type(schema.get('items'))}]"
    if schema_type == "object":
        additional = schema.get("additionalProperties")
        if isinstance(additional, dict):
            return f"dict[str, {schema_to_type(additional)}]"
        if additional is True:
            return "dict[str, Any]"
        if schema.get("properties"):
            # Nested anonymous objects are emitted as loose dicts.
            return "dict[str, Any]"
        return "dict[str, Any]"

    return "Any"


def join_union(parts: list[str]) -> str:
    deduped: list[str] = []
    for part in parts:
        if part not in deduped:
            deduped.append(part)
    return " | ".join(deduped) if deduped else "Any"


def render_schema(name: str, schema: dict[str, Any]) -> str:
    if "enum" in schema:
        literals = ", ".join(repr(v) for v in schema["enum"])
        return f"{name} = Literal[{literals}]\n"

    if "$ref" in schema:
        return f"{name} = {schema_to_type(schema)}\n"

    schema_type = schema.get("type")

    if schema_type == "object":
        props = schema.get("properties", {})
        required = set(schema.get("required", []))
        description = schema.get("description")

        if not props:
            return f"{name} = dict[str, Any]\n"

        invalid_keys = [key for key in props if not is_valid_identifier(key)]
        if invalid_keys:
            # Fallback for non-identifier JSON keys.
            lines = [f"{name} = TypedDict(\n", f"    \"{name}\",\n", "    {\n"]
            for key in sorted(props):
                py_type = schema_to_type(props[key])
                lines.append(f"        \"{quote_string(key)}\": {py_type},\n")
            lines.append("    },\n")
            lines.append("    total=False,\n")
            lines.append(")\n")
            return "".join(lines)

        lines: list[str] = [f"class {name}(TypedDict, total=False):\n"]
        if description:
            lines.append(f"    \"\"\"{description}\"\"\"\n")
        for key in sorted(props):
            py_type = schema_to_type(props[key])
            wrapper = "Required" if key in required else "NotRequired"
            lines.append(f"    {key}: {wrapper}[{py_type}]\n")
        return "".join(lines) + "\n"

    rendered = schema_to_type(schema)
    return f"{name} = {rendered}\n"


def build_output(spec: dict[str, Any]) -> str:
    schemas = spec.get("components", {}).get("schemas", {})
    names = sorted(schemas)

    header = [
        "# This file is auto-generated by packages/contracts/scripts/generate_python_types.py\n",
        "# Do not edit this file directly.\n\n",
        "from __future__ import annotations\n\n",
        "from typing import Any, Literal, NotRequired, Required, TypedDict\n\n",
    ]

    body: list[str] = []
    for name in names:
        body.append(render_schema(name, schemas[name]))

    exports = "__all__ = [\n" + "".join(f"    \"{name}\",\n" for name in names) + "]\n"
    return "".join(header + body + ["\n", exports])


def run(check_only: bool) -> int:
    spec = json.loads(OPENAPI_PATH.read_text())
    rendered = build_output(spec)

    if check_only:
        if not OUTPUT_PATH.exists():
            print(f"[contracts] missing generated file: {OUTPUT_PATH}")
            return 1

        current = OUTPUT_PATH.read_text()
        if current != rendered:
            print("[contracts] generated contracts are out of date")
            diff = difflib.unified_diff(
                current.splitlines(),
                rendered.splitlines(),
                fromfile=str(OUTPUT_PATH),
                tofile=f"{OUTPUT_PATH} (expected)",
                lineterm="",
            )
            for line in diff:
                print(line)
            return 1

        print("[contracts] generated contracts are up to date")
        return 0

    OUTPUT_PATH.write_text(rendered)
    print(f"[contracts] wrote {OUTPUT_PATH}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated output is stale")
    args = parser.parse_args()
    return run(check_only=args.check)


if __name__ == "__main__":
    sys.exit(main())
