/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/simulations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List simulations */
        get: operations["listSimulations"];
        put?: never;
        /**
         * Create a new simulation draft
         * @description Creates a pending simulation draft. For dataset=nemotron_usa, any unsupported filter key must be rejected with 400 and error.code=UNSUPPORTED_FILTER. Rejection is strict: no partial acceptance and no silent key dropping.
         */
        post: operations["createSimulation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete simulation */
        delete: operations["deleteSimulation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulations/{id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start simulation run
         * @description Starts asynchronous inference and returns 202. Clarification loop is optional and non-blocking. If use_refined_prompt=true, refined_policy_text is used when available; otherwise base policy_text is used.
         */
        post: operations["runSimulation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulations/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get run progress */
        get: operations["getSimulationStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulations/{id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get aggregated results */
        get: operations["getSimulationResults"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulations/{id}/clarifications/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate next clarification question
         * @description Generates one clarification question via local Gemma runtime. Clarification generation is draft-only and does not change simulation lifecycle status.
         */
        post: operations["generateClarification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clarifications/{clarification_id}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Answer clarification question
         * @description Processes clarification answer via local Gemma runtime, updates refined policy text, and optionally opens the next clarification turn. Clarification flow is pending-only with a hard max of 3 turns.
         */
        post: operations["answerClarification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulations/{id}/clarifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get clarification state */
        get: operations["getClarificationState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulations/{id}/challenge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate challenge from weak outcomes */
        post: operations["generateChallenge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/challenges/{challenge_id}/followup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit followup and get next challenge */
        post: operations["submitFollowup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List synthetic datasets */
        get: operations["listDatasets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulations/{id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export raw responses as CSV */
        get: operations["exportSimulationCsv"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        SimulationStatus: "pending" | "running" | "completed" | "failed";
        /** @enum {string} */
        RuntimeProfile: "interactive" | "balanced" | "thorough" | "auto";
        /** @enum {string} */
        ClarificationStatus: "none" | "in_progress" | "resolved";
        /** @enum {string} */
        ClarificationQuestionState: "open" | "resolved";
        Meta: {
            request_id?: string;
            device_profile?: string;
            total?: number;
            page?: number;
            limit?: number;
        };
        ErrorObject: {
            code: string;
            message: string;
        };
        ErrorEnvelope: {
            data: null;
            error: components["schemas"]["ErrorObject"];
            meta: components["schemas"]["Meta"];
        };
        /** @description For dataset=nemotron_usa, supported filter keys are states, age_range, sex, marital_status, education_level, occupation. Unsupported keys income_brackets, household_income, ethnicity must trigger 400 with error.code=UNSUPPORTED_FILTER. */
        FilterSet: {
            states?: string[];
            age_range?: number[];
            sex?: string[];
            marital_status?: string[];
            education_level?: string[];
            occupation?: string[];
        };
        CreateSimulationRequest: {
            title: string;
            policy_text: string;
            dataset: string;
            sample_size: number;
            filters?: components["schemas"]["FilterSet"];
        };
        SimulationDraft: {
            id: string;
            title: string;
            policy_text: string;
            status: components["schemas"]["SimulationStatus"];
            dataset: string;
            sample_size: number;
            filters?: components["schemas"]["FilterSet"];
            /** Format: date-time */
            created_at: string;
        };
        CreateSimulationEnvelope: {
            data: components["schemas"]["SimulationDraft"];
            error: null;
            meta: components["schemas"]["Meta"];
        };
        RunSimulationRequest: {
            profile?: components["schemas"]["RuntimeProfile"];
            max_duration_seconds?: number;
            /** @default true */
            allow_sample_clamp: boolean;
            /**
             * @description When true, refined_policy_text is used if available; otherwise policy_text is used.
             * @default true
             */
            use_refined_prompt: boolean;
        };
        RunAcceptedData: {
            id: string;
            status: components["schemas"]["SimulationStatus"];
            /** Format: date-time */
            started_at: string;
            estimated_seconds: number;
            runtime_profile: components["schemas"]["RuntimeProfile"];
            effective_sample_size: number;
        };
        RunAcceptedEnvelope: {
            data: components["schemas"]["RunAcceptedData"];
            error: null;
            meta: components["schemas"]["Meta"];
        };
        RunTelemetry: {
            retry_count: number;
            invalid_output_count: number;
            failure_code: string | null;
            failure_message: string | null;
            failed_persona_id: string | null;
        };
        SimulationStatusData: {
            id: string;
            status: components["schemas"]["SimulationStatus"];
            agents_total: number;
            agents_completed: number;
            progress_pct: number;
            estimated_seconds_remaining: number;
            runtime_profile: components["schemas"]["RuntimeProfile"];
            effective_sample_size: number;
            run_telemetry: components["schemas"]["RunTelemetry"];
        };
        SimulationStatusEnvelope: {
            data: components["schemas"]["SimulationStatusData"];
            error: null;
            meta: components["schemas"]["Meta"];
        };
        /** @description Map of approval bucket (1-5) to count. */
        ApprovalDistribution: {
            [key: string]: number;
        };
        Summary: {
            mean_approval: number;
            approval_distribution: components["schemas"]["ApprovalDistribution"];
            dominant_emotion: string;
            behavioral_change_pct: number;
        };
        RunConfig: {
            runtime_profile: components["schemas"]["RuntimeProfile"];
            effective_sample_size: number;
        };
        MeanApprovalCount: {
            mean_approval: number;
            count: number;
        };
        DemographicBreakdown: {
            by_age_group: {
                [key: string]: components["schemas"]["MeanApprovalCount"];
            };
            by_marital_status: {
                [key: string]: components["schemas"]["MeanApprovalCount"];
            };
            by_state: {
                [key: string]: number;
            };
            by_occupation_group: {
                [key: string]: unknown;
            };
        };
        EmotionProfile: {
            [key: string]: number;
        };
        RepresentativeQuote: {
            persona_id: string;
            name: string;
            age: number;
            occupation: string;
            city: string;
            state: string;
            approval: number;
            emotion: string;
            rationale: string;
        };
        SimulationResultsData: {
            id: string;
            summary: components["schemas"]["Summary"];
            run_config: components["schemas"]["RunConfig"];
            demographic_breakdown: components["schemas"]["DemographicBreakdown"];
            emotion_profile: components["schemas"]["EmotionProfile"];
            representative_quotes: components["schemas"]["RepresentativeQuote"][];
            raw_responses_url: string;
        };
        SimulationResultsEnvelope: {
            data: components["schemas"]["SimulationResultsData"];
            error: null;
            meta: components["schemas"]["Meta"];
        };
        SimulationListItem: {
            id: string;
            title: string;
            status: components["schemas"]["SimulationStatus"];
            sample_size: number;
            mean_approval: number | null;
            /** Format: date-time */
            created_at: string;
            completed_at: string | null;
        };
        SimulationListEnvelope: {
            data: components["schemas"]["SimulationListItem"][];
            error: null;
            meta: components["schemas"]["Meta"];
        };
        DeleteSimulationData: {
            id: string;
            deleted: boolean;
        };
        DeleteSimulationEnvelope: {
            data: components["schemas"]["DeleteSimulationData"];
            error: null;
            meta: components["schemas"]["Meta"];
        };
        GenerateClarificationRequest: {
            focus: string;
        };
        ClarificationQuestionData: {
            clarification_id: string;
            simulation_id: string;
            question_text: string;
            rationale: string;
            status: components["schemas"]["ClarificationQuestionState"];
            turn_index: number;
        };
        ClarificationQuestionEnvelope: {
            data: components["schemas"]["ClarificationQuestionData"];
            error: null;
            meta: components["schemas"]["Meta"];
        };
        ClarificationAnswerRequest: {
            simulation_id: string;
            user_response: string;
        };
        ClarificationAnswerData: {
            simulation_id: string;
            clarification_status: components["schemas"]["ClarificationStatus"];
            refined_policy_text: string;
            next_clarification_id?: string | null;
            next_question_text?: string | null;
        };
        ClarificationAnswerEnvelope: {
            data: components["schemas"]["ClarificationAnswerData"];
            error: null;
            meta: components["schemas"]["Meta"];
        };
        ClarificationStateData: {
            simulation_id: string;
            clarification_status: components["schemas"]["ClarificationStatus"];
            has_open_question: boolean;
            latest_refined_policy_text: string;
        };
        ClarificationStateEnvelope: {
            data: components["schemas"]["ClarificationStateData"];
            error: null;
            meta: components["schemas"]["Meta"];
        };
        GenerateChallengeRequest: {
            focus: string;
        };
        ChallengeEvidence: {
            segment: string;
            mean_approval: number;
            top_concern: string;
        };
        ChallengeData: {
            challenge_id: string;
            challenge_text: string;
            evidence: components["schemas"]["ChallengeEvidence"];
        };
        ChallengeEnvelope: {
            data: components["schemas"]["ChallengeData"];
            error: null;
            meta: components["schemas"]["Meta"];
        };
        ChallengeFollowupRequest: {
            simulation_id: string;
            user_response: string;
        };
        ChallengeFollowupData: {
            followup_text: string;
            suggested_policy_refinement: string;
            next_challenge_id: string;
        };
        ChallengeFollowupEnvelope: {
            data: components["schemas"]["ChallengeFollowupData"];
            error: null;
            meta: components["schemas"]["Meta"];
        };
        DatasetItem: {
            id: string;
            name: string;
            description: string;
            size?: number;
            attributes?: string[];
            license?: string;
            status?: string;
        };
        DatasetsEnvelope: {
            data: components["schemas"]["DatasetItem"][];
            error: null;
            meta: components["schemas"]["Meta"];
        };
    };
    responses: never;
    parameters: {
        SimulationIdPath: string;
        ClarificationIdPath: string;
        ChallengeIdPath: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listSimulations: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                status?: components["schemas"]["SimulationStatus"];
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Simulation history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationListEnvelope"];
                };
            };
        };
    };
    createSimulation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSimulationRequest"];
            };
        };
        responses: {
            /** @description Draft created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateSimulationEnvelope"];
                };
            };
            /** @description Validation or unsupported filter error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    deleteSimulation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SimulationIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteSimulationEnvelope"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    runSimulation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SimulationIdPath"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RunSimulationRequest"];
            };
        };
        responses: {
            /** @description Run accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunAcceptedEnvelope"];
                };
            };
            /** @description Invalid run request payload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Simulation not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Lifecycle conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getSimulationStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SimulationIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationStatusEnvelope"];
                };
            };
            /** @description Simulation not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getSimulationResults: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SimulationIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Completed results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationResultsEnvelope"];
                };
            };
        };
    };
    generateClarification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SimulationIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateClarificationRequest"];
            };
        };
        responses: {
            /** @description Clarification generated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClarificationQuestionEnvelope"];
                };
            };
            /** @description Invalid request payload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Simulation not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Lifecycle conflict for non-pending simulation */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Gemma/Ollama runtime failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    answerClarification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clarification_id: components["parameters"]["ClarificationIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClarificationAnswerRequest"];
            };
        };
        responses: {
            /** @description Clarification answer processed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClarificationAnswerEnvelope"];
                };
            };
            /** @description Invalid request payload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Simulation or active clarification not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Lifecycle conflict for non-pending simulation */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Gemma/Ollama runtime failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getClarificationState: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SimulationIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current clarification state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClarificationStateEnvelope"];
                };
            };
            /** @description Simulation not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    generateChallenge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SimulationIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateChallengeRequest"];
            };
        };
        responses: {
            /** @description Challenge generated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengeEnvelope"];
                };
            };
        };
    };
    submitFollowup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                challenge_id: components["parameters"]["ChallengeIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChallengeFollowupRequest"];
            };
        };
        responses: {
            /** @description Followup accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengeFollowupEnvelope"];
                };
            };
        };
    };
    listDatasets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Available datasets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetsEnvelope"];
                };
            };
        };
    };
    exportSimulationCsv: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SimulationIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSV stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
        };
    };
}
