# This file is auto-generated by packages/contracts/scripts/generate_python_types.py
# Do not edit this file directly.

from __future__ import annotations

from typing import Any, Literal, NotRequired, Required, TypedDict

ApprovalDistribution = dict[str, Any]
class ChallengeData(TypedDict, total=False):
    challenge_id: Required[str]
    challenge_text: Required[str]
    evidence: Required[ChallengeEvidence]

class ChallengeEnvelope(TypedDict, total=False):
    data: Required[ChallengeData]
    error: Required[None]
    meta: Required[Meta]

class ChallengeEvidence(TypedDict, total=False):
    mean_approval: Required[float]
    segment: Required[str]
    top_concern: Required[str]

class ChallengeFollowupData(TypedDict, total=False):
    followup_text: Required[str]
    next_challenge_id: Required[str]
    suggested_policy_refinement: Required[str]

class ChallengeFollowupEnvelope(TypedDict, total=False):
    data: Required[ChallengeFollowupData]
    error: Required[None]
    meta: Required[Meta]

class ChallengeFollowupRequest(TypedDict, total=False):
    simulation_id: Required[str]
    user_response: Required[str]

class ClarificationAnswerData(TypedDict, total=False):
    clarification_status: Required[ClarificationStatus]
    next_clarification_id: NotRequired[str | None]
    next_question_text: NotRequired[str | None]
    refined_policy_text: Required[str]
    simulation_id: Required[str]

class ClarificationAnswerEnvelope(TypedDict, total=False):
    data: Required[ClarificationAnswerData]
    error: Required[None]
    meta: Required[Meta]

class ClarificationAnswerRequest(TypedDict, total=False):
    simulation_id: Required[str]
    user_response: Required[str]

class ClarificationQuestionData(TypedDict, total=False):
    clarification_id: Required[str]
    question_text: Required[str]
    rationale: Required[str]
    simulation_id: Required[str]
    status: Required[ClarificationQuestionState]
    turn_index: Required[int]

class ClarificationQuestionEnvelope(TypedDict, total=False):
    data: Required[ClarificationQuestionData]
    error: Required[None]
    meta: Required[Meta]

ClarificationQuestionState = Literal['open', 'resolved']
class ClarificationStateData(TypedDict, total=False):
    clarification_status: Required[ClarificationStatus]
    has_open_question: Required[bool]
    latest_refined_policy_text: Required[str]
    simulation_id: Required[str]

class ClarificationStateEnvelope(TypedDict, total=False):
    data: Required[ClarificationStateData]
    error: Required[None]
    meta: Required[Meta]

ClarificationStatus = Literal['none', 'in_progress', 'resolved']
class CreateSimulationEnvelope(TypedDict, total=False):
    data: Required[SimulationDraft]
    error: Required[None]
    meta: Required[Meta]

class CreateSimulationRequest(TypedDict, total=False):
    dataset: Required[str]
    filters: NotRequired[FilterSet]
    policy_text: Required[str]
    sample_size: Required[int]
    title: Required[str]

class DatasetItem(TypedDict, total=False):
    attributes: NotRequired[list[str]]
    description: Required[str]
    id: Required[str]
    license: NotRequired[str]
    name: Required[str]
    size: NotRequired[int]
    status: NotRequired[str]

class DatasetsEnvelope(TypedDict, total=False):
    data: Required[list[DatasetItem]]
    error: Required[None]
    meta: Required[Meta]

class DeleteSimulationData(TypedDict, total=False):
    deleted: Required[bool]
    id: Required[str]

class DeleteSimulationEnvelope(TypedDict, total=False):
    data: Required[DeleteSimulationData]
    error: Required[None]
    meta: Required[Meta]

class DemographicBreakdown(TypedDict, total=False):
    by_age_group: Required[dict[str, MeanApprovalCount]]
    by_marital_status: Required[dict[str, MeanApprovalCount]]
    by_occupation_group: Required[dict[str, Any]]
    by_state: Required[dict[str, float]]

EmotionProfile = dict[str, Any]
class ErrorEnvelope(TypedDict, total=False):
    data: Required[None]
    error: Required[ErrorObject]
    meta: Required[Meta]

class ErrorObject(TypedDict, total=False):
    code: Required[str]
    message: Required[str]

class FilterSet(TypedDict, total=False):
    """For dataset=nemotron_usa, supported filter keys are states, age_range, sex, marital_status, education_level, occupation. Unsupported keys income_brackets, household_income, ethnicity must trigger 400 with error.code=UNSUPPORTED_FILTER."""
    age_range: NotRequired[list[int]]
    education_level: NotRequired[list[str]]
    marital_status: NotRequired[list[str]]
    occupation: NotRequired[list[str]]
    sex: NotRequired[list[str]]
    states: NotRequired[list[str]]

class GenerateChallengeRequest(TypedDict, total=False):
    focus: Required[str]

class GenerateClarificationRequest(TypedDict, total=False):
    focus: Required[str]

class MeanApprovalCount(TypedDict, total=False):
    count: Required[int]
    mean_approval: Required[float]

class Meta(TypedDict, total=False):
    device_profile: NotRequired[str]
    limit: NotRequired[int]
    page: NotRequired[int]
    request_id: NotRequired[str]
    total: NotRequired[int]

class RepresentativeQuote(TypedDict, total=False):
    age: Required[int]
    approval: Required[int]
    city: Required[str]
    emotion: Required[str]
    name: Required[str]
    occupation: Required[str]
    persona_id: Required[str]
    rationale: Required[str]
    state: Required[str]

class RunAcceptedData(TypedDict, total=False):
    effective_sample_size: Required[int]
    estimated_seconds: Required[int]
    id: Required[str]
    runtime_profile: Required[RuntimeProfile]
    started_at: Required[str]
    status: Required[SimulationStatus]

class RunAcceptedEnvelope(TypedDict, total=False):
    data: Required[RunAcceptedData]
    error: Required[None]
    meta: Required[Meta]

class RunConfig(TypedDict, total=False):
    effective_sample_size: Required[int]
    runtime_profile: Required[RuntimeProfile]

class RunSimulationRequest(TypedDict, total=False):
    allow_sample_clamp: NotRequired[bool]
    max_duration_seconds: NotRequired[int]
    profile: NotRequired[RuntimeProfile]
    use_refined_prompt: NotRequired[bool]

RuntimeProfile = Literal['interactive', 'balanced', 'thorough', 'auto']
class SimulationDraft(TypedDict, total=False):
    created_at: Required[str]
    dataset: Required[str]
    filters: NotRequired[FilterSet]
    id: Required[str]
    policy_text: Required[str]
    sample_size: Required[int]
    status: Required[SimulationStatus]
    title: Required[str]

class SimulationListEnvelope(TypedDict, total=False):
    data: Required[list[SimulationListItem]]
    error: Required[None]
    meta: Required[Meta]

class SimulationListItem(TypedDict, total=False):
    completed_at: Required[str | None]
    created_at: Required[str]
    id: Required[str]
    mean_approval: Required[float | None]
    sample_size: Required[int]
    status: Required[SimulationStatus]
    title: Required[str]

class SimulationResultsData(TypedDict, total=False):
    demographic_breakdown: Required[DemographicBreakdown]
    emotion_profile: Required[EmotionProfile]
    id: Required[str]
    raw_responses_url: Required[str]
    representative_quotes: Required[list[RepresentativeQuote]]
    run_config: Required[RunConfig]
    summary: Required[Summary]

class SimulationResultsEnvelope(TypedDict, total=False):
    data: Required[SimulationResultsData]
    error: Required[None]
    meta: Required[Meta]

SimulationStatus = Literal['pending', 'running', 'completed', 'failed']
class SimulationStatusData(TypedDict, total=False):
    agents_completed: Required[int]
    agents_total: Required[int]
    effective_sample_size: Required[int]
    estimated_seconds_remaining: Required[int]
    id: Required[str]
    progress_pct: Required[float]
    runtime_profile: Required[RuntimeProfile]
    status: Required[SimulationStatus]

class SimulationStatusEnvelope(TypedDict, total=False):
    data: Required[SimulationStatusData]
    error: Required[None]
    meta: Required[Meta]

class Summary(TypedDict, total=False):
    approval_distribution: Required[ApprovalDistribution]
    behavioral_change_pct: Required[float]
    dominant_emotion: Required[str]
    mean_approval: Required[float]


__all__ = [
    "ApprovalDistribution",
    "ChallengeData",
    "ChallengeEnvelope",
    "ChallengeEvidence",
    "ChallengeFollowupData",
    "ChallengeFollowupEnvelope",
    "ChallengeFollowupRequest",
    "ClarificationAnswerData",
    "ClarificationAnswerEnvelope",
    "ClarificationAnswerRequest",
    "ClarificationQuestionData",
    "ClarificationQuestionEnvelope",
    "ClarificationQuestionState",
    "ClarificationStateData",
    "ClarificationStateEnvelope",
    "ClarificationStatus",
    "CreateSimulationEnvelope",
    "CreateSimulationRequest",
    "DatasetItem",
    "DatasetsEnvelope",
    "DeleteSimulationData",
    "DeleteSimulationEnvelope",
    "DemographicBreakdown",
    "EmotionProfile",
    "ErrorEnvelope",
    "ErrorObject",
    "FilterSet",
    "GenerateChallengeRequest",
    "GenerateClarificationRequest",
    "MeanApprovalCount",
    "Meta",
    "RepresentativeQuote",
    "RunAcceptedData",
    "RunAcceptedEnvelope",
    "RunConfig",
    "RunSimulationRequest",
    "RuntimeProfile",
    "SimulationDraft",
    "SimulationListEnvelope",
    "SimulationListItem",
    "SimulationResultsData",
    "SimulationResultsEnvelope",
    "SimulationStatus",
    "SimulationStatusData",
    "SimulationStatusEnvelope",
    "Summary",
]
