/**
 * GuidePage — How InfiniPol works, step-by-step reference.
 * Rendered inside the main app Layout (AppHeader + AppFooter).
 */

import { Link } from 'react-router-dom'
import {
  Box, Container, Stack, Text, Group, Badge,
  ThemeIcon, Divider, SimpleGrid, Anchor,
} from '@mantine/core'
import {
  FileText, SlidersHorizontal, Play, BarChart2,
  GitCompare, Zap, MessageSquare, ShieldQuestion,
  ChevronRight,
} from 'lucide-react'
import { Layout } from '@/components/layout/Layout'

// ── Section data ──────────────────────────────────────────────────────────────

const STEPS = [
  {
    n: '01',
    icon: <FileText size={20} />,
    title: 'Write your policy prompt',
    body: `Describe the policy in plain language: its scope, who it affects, the mechanism, estimated costs, and expected benefits. A richer prompt yields more nuanced persona responses. Aim for 3–8 sentences.`,
  },
  {
    n: '02',
    icon: <ShieldQuestion size={20} />,
    title: 'Clarification (optional)',
    body: `If InfiniPol detects ambiguities in your draft it will ask 2–4 targeted questions before running. Answering them sharpens the prompt and produces more accurate approval scores. You can skip this step.`,
  },
  {
    n: '03',
    icon: <SlidersHorizontal size={20} />,
    title: 'Set your audience filters',
    body: `Narrow the sample by US state, age group, sex, education level, occupation category, or marital status, or leave all filters blank for a nationally representative sample of 300,000+ personas.`,
  },
  {
    n: '04',
    icon: <Play size={20} />,
    title: 'Run the simulation',
    body: `InfiniPol draws a stratified sample from the NVIDIA Nemotron-Personas dataset and has Gemma score each persona's reaction to your policy. The full run typically completes in under two minutes.`,
  },
  {
    n: '05',
    icon: <BarChart2 size={20} />,
    title: 'Review results',
    body: `The Results page surfaces: a mean approval score (1–5), an emotion profile (joy, trust, fear, anger, surprise, sadness), a behavioral-change estimate, demographic breakdowns, and representative persona quotes.`,
  },
  {
    n: '06',
    icon: <GitCompare size={20} />,
    title: 'Compare or challenge',
    body: `Run a second simulation with tweaked wording and compare both side-by-side, or use AI Challenge Mode to let Gemma stress-test your weakest segment, emotional bias, or demographic gap.`,
  },
  {
    n: '07',
    icon: <Zap size={20} />,
    title: 'Export & cite',
    body: `Download the raw persona responses as CSV, generate a PDF summary, or copy a citable quote directly from any persona card to use in presentations or reports.`,
  },
]

const FAQS = [
  {
    q: 'What is a "synthetic persona"?',
    a: 'Each persona is a synthetic US resident generated by NVIDIA\'s Nemotron-Personas model, trained on real demographic distributions from the American Community Survey. They hold internally consistent beliefs, preferences, and demographic attributes, but are not real people.',
  },
  {
    q: 'How accurate are the approval scores?',
    a: 'Scores reflect how a demographically matched synthetic population responds to your policy description as written. Accuracy scales with prompt quality: vague or misleading prompts produce less reliable results. Treat scores as directional signals, not polling data.',
  },
  {
    q: 'Can I use InfiniPol for real policy decisions?',
    a: 'InfiniPol is a research and exploration tool. Synthetic simulations complement, but do not replace, real-world polling, focus groups, or stakeholder consultation. Always validate with primary research before acting on results.',
  },
  {
    q: 'Where is my data stored?',
    a: 'Simulation metadata and results are stored in your browser\'s localStorage. Nothing is sent to a remote server beyond the API call needed to run each simulation. Clearing browser storage removes all your simulations.',
  },
  {
    q: 'What does Challenge Mode do?',
    a: 'Challenge Mode sends your results to Gemma with a specific adversarial focus: weak segment, behavioral-change gap, emotion bias, or demographic disparity. Gemma returns targeted critique you can use to refine your policy before re-running.',
  },
  {
    q: 'How do I compare two simulations?',
    a: 'Open the Compare page from the top nav, then pick any two completed simulations. InfiniPol shows delta approval scores, diverging emotion profiles, and side-by-side distribution charts.',
  },
]

// ── Components ────────────────────────────────────────────────────────────────

function StepCard({ step }: { step: typeof STEPS[number] }) {
  return (
    <Group gap={20} align="flex-start" wrap="nowrap">
      <Stack gap={0} align="center" style={{ flexShrink: 0 }}>
        <ThemeIcon
          size={44}
          radius={10}
          style={{
            backgroundColor: 'var(--color-accent-primary-subtle)',
            color: 'var(--color-accent-primary)',
          }}
        >
          {step.icon}
        </ThemeIcon>
        <Text
          fw={800}
          size="xs"
          mt={6}
          style={{
            color: 'var(--color-accent-primary)',
            opacity: 0.5,
            letterSpacing: '0.04em',
            fontFamily: 'Source Serif 4, serif',
          }}
        >
          {step.n}
        </Text>
      </Stack>
      <Stack gap={6} pt={4}>
        <Text fw={700} size="sm" c="var(--color-text-primary)">{step.title}</Text>
        <Text size="sm" c="var(--color-text-secondary)" lh={1.65}>{step.body}</Text>
      </Stack>
    </Group>
  )
}

function FaqItem({ q, a }: { q: string; a: string }) {
  return (
    <Box
      style={{
        backgroundColor: 'var(--color-bg-surface)',
        border: '1px solid var(--color-border-subtle)',
        borderRadius: 10,
        padding: '20px 24px',
      }}
    >
      <Text fw={700} size="sm" c="var(--color-text-primary)" mb={8}>{q}</Text>
      <Text size="sm" c="var(--color-text-secondary)" lh={1.65}>{a}</Text>
    </Box>
  )
}

// ── Page ──────────────────────────────────────────────────────────────────────

export default function GuidePage() {
  return (
    <Layout>
      <Box py={56} style={{ backgroundColor: 'var(--color-bg-base)', minHeight: '100%' }}>
        <Container size="md">
          <Stack gap={56}>

            {/* Page header */}
            <Stack gap="sm">
              <Badge
                size="md"
                variant="light"
                style={{
                  backgroundColor: 'var(--color-accent-primary-subtle)',
                  color: 'var(--color-accent-primary)',
                  border: '1px solid var(--color-accent-primary)',
                  fontWeight: 600,
                  width: 'fit-content',
                }}
              >
                User Guide
              </Badge>
              <Text
                component="h1"
                style={{
                  fontSize: 'clamp(1.8rem, 4vw, 2.6rem)',
                  fontWeight: 800,
                  lineHeight: 1.1,
                  letterSpacing: '-0.03em',
                  color: 'var(--color-text-primary)',
                  fontFamily: 'Source Serif 4, serif',
                  margin: 0,
                }}
              >
                How InfiniPol works
              </Text>
              <Text size="md" c="var(--color-text-secondary)" lh={1.7} style={{ maxWidth: 560 }}>
                A step-by-step walkthrough of the simulation pipeline, from writing your first
                policy prompt to exporting results.
              </Text>
            </Stack>

            <Divider style={{ borderColor: 'var(--color-border-subtle)' }} />

            {/* Steps */}
            <Stack gap={0}>
              <Text
                fw={700}
                mb={32}
                style={{
                  fontSize: '1.2rem',
                  color: 'var(--color-text-primary)',
                  fontFamily: 'Source Serif 4, serif',
                }}
              >
                Simulation workflow
              </Text>
              <Stack gap={32}>
                {STEPS.map((s) => (
                  <StepCard key={s.n} step={s} />
                ))}
              </Stack>
            </Stack>

            <Divider style={{ borderColor: 'var(--color-border-subtle)' }} />

            {/* FAQ */}
            <Stack gap={0}>
              <Text
                fw={700}
                mb={24}
                style={{
                  fontSize: '1.2rem',
                  color: 'var(--color-text-primary)',
                  fontFamily: 'Source Serif 4, serif',
                }}
              >
                Frequently asked questions
              </Text>
              <SimpleGrid cols={{ base: 1, sm: 2 }} spacing="md">
                {FAQS.map((f) => (
                  <FaqItem key={f.q} q={f.q} a={f.a} />
                ))}
              </SimpleGrid>
            </Stack>

            <Divider style={{ borderColor: 'var(--color-border-subtle)' }} />

            {/* CTA */}
            <Group gap="xs" align="center">
              <Text size="sm" c="var(--color-text-secondary)">
                Ready to try it?
              </Text>
              <Anchor
                component={Link}
                to="/simulations/new"
                size="sm"
                fw={600}
                style={{ color: 'var(--color-accent-primary)', textDecoration: 'none', display: 'flex', alignItems: 'center', gap: 4 }}
              >
                Run a simulation <ChevronRight size={14} />
              </Anchor>
            </Group>

            {/* Dataset attribution */}
            <Box
              style={{
                backgroundColor: 'var(--color-bg-surface)',
                border: '1px solid var(--color-border-subtle)',
                borderRadius: 8,
                padding: '16px 20px',
              }}
            >
              <Group gap="xs" align="center" mb={6}>
                <MessageSquare size={14} color="var(--color-text-tertiary)" />
                <Text size="xs" fw={600} c="var(--color-text-tertiary)" style={{ textTransform: 'uppercase', letterSpacing: '0.06em' }}>
                  Dataset
                </Text>
              </Group>
              <Text size="xs" c="var(--color-text-tertiary)" lh={1.6}>
                Synthetic personas are sourced from{' '}
                <Anchor
                  href="https://huggingface.co/datasets/nvidia/Nemotron-Personas"
                  target="_blank"
                  rel="noopener noreferrer"
                  size="xs"
                  style={{ color: 'var(--color-text-secondary)' }}
                >
                  NVIDIA Nemotron-Personas
                </Anchor>{' '}
                (CC BY 4.0). These are AI-generated synthetic individuals and do not represent real people.
                Simulation results should not be used as a substitute for empirical research or real-world polling.
              </Text>
            </Box>

          </Stack>
        </Container>
      </Box>
    </Layout>
  )
}
